sizes:
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59

heights:
  - 48
  - 51
  - 57
  - 60
  - 63
  - 66
  - 69
  - 75
  - 78

workstations:
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  

price:  
  - 50
  - 75
  - 100
  - 125
  - 150
  - 200
  - 300
  - 400
  - 500

makes:
 - Hero
 - Solar
 - Montra
 - RAND
 - BTWN
 - Others

models: 
  - trek
  - rock rider
  - river side
  - Others

extras:
  - Lock
  - Helmet
  - Lights
  - Bell
  - Reflectors
  - Basket
