# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a365035e8fca25cbbb4ee355a2e18eb352af59d1c64c82b31ccf833c6648a0ed34dce52b4df7b796e665cea33dc74575a506d9df38ed2bfc0385d12a80cda913

test:
  secret_key_base: d9721b9d0fbe63871e79c21ba32bc9735b4c1aee3bc5b9fc5510a51d661dc494cb5fc36584978acddc49c9e8a7d5199587dfdea36859d6348ca6522d697ffd79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
